### ISSUE TITLE
The current state is set to the initial state after scene switching

### ISSUE THREAD

**Issue by Senne021** [hendrik-schulte/UnityEnhanced#1]
The current state is set to the initial state after scene switching. This happens in each windows pc standalone build and sometimes even in the unity editor. Changing settings like "log to file" or "log to console" fixes this error in the editor, which is why i think it could be a problem of the execution order that is affected by the speed.
I have created a simple [project](https://github.com/Senn3/UE-Bug-Scene-Switch) to reproduce this error.

**Comment by hendrik-schulte** [comment]
Hmm this indeed is a problem. Looks like Scriptable Objects get reset from their Serialization Layer as soon as no Scene Object references it anymore which is the case when a Scene Change occurs. I think I found a similar issue here: 

https://answers.unity.com/questions/1501743/scriptable-object-resets-randomly-between-scenes.html

The field of question is the following (StateManager):

`        
[NonSerialized] private State _state;
`
This field stores the currently active state. When entering play mode, it is null. When initialized, the StateManager checks, if its null and enters the Initial state if true. However, I wasn't aware that it also gets reset when changing a scene.

Problem is that _state is meant to be forgotten, for example when leaving Play mode. Scriptable Objects are not designed to "live" in a scene and they do not get callbacks when play mode is entered or such. 
I can think of some approaches for a solution:
- One could just Serialize the _state field, but then the state would also be persistent when leaving and reentering play mode. This should not be a problem in the build though since the object should reset when restarting the application. Ill look into that
- As a workaround you could try to reference these StateManagers by a persistent Scene Object (marked as "Dont destroy on load"). This may keep the instance of that StateManager alive during a scene change.

**Comment by hendrik-schulte** [comment]
I think I solved your issue!

I only needed to define the StateManager asset as 

`
hideFlags = HideFlags.DontUnloadUnusedAsset;
`

and it will not be unloaded when changing the scene. No extra object required. Pull the latest commit to obtain the fix. Please confirm this fixes the problems for you, too.

Cheers!
